# Generated by Django 5.1.7 on 2025-03-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('SEEN', 'Seen')], default='SENT', max_length=10),
        ),
    ]
