# Generated by Django 5.1.4 on 2024-12-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
