# Generated by Django 5.1.4 on 2025-01-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_otp_created_at_otp_is_valid_alter_otp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=250),
        ),
    ]
